language: cpp
sudo: required
compiler:
- g++
os:
- linux

before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get install -y g++
before_script:
- g++ -std=c++0x  -o main main.cpp 
script: 
  ./main
branches:
  only:
  - master
  - dev
  - "/^v\\d+\\./"
env:
  global:
  - LANG="en_US.UTF-8"
  
